### ISSUE TITLE
the script don't work 

### ISSUE THREAD

**Issue by toutpuissantged** [jithumon/tgbot#21]

**Comment by jithumon** [comment]
which script?

**Comment by toutpuissantged** [comment]
`$ python -m tg_bot
Traceback (most recent call last):
  File "C:\Users\gedeon\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\gedeon\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\gedeon\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "D:\Code\Python-Project\tgbot\tg_bot\__init__.py", line 108, in <module>
    BMERNU_SCUT_SRELFTI = int(Config.BMERNU_SCUT_SRELFTI)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

**Comment by jithumon** [comment]
Fixed, try again.

**Comment by toutpuissantged** [comment]
okey
